### ISSUE TITLE
Errors trying to use monodeploy config. 

### ISSUE THREAD

**Issue by mattthaber** [tophat/monodeploy#297]
**Describe the bug**

Trying to use the `--config-file` flag to pass monodeploy a config, and have ran into multiple issues

**To reproduce**

```
yarn add -D monodeploy@^2.3.0
```

create file `monodeploy.config.js` with contents
```
import type { MonodeployConfiguration }  from '@monodeploy/types'
import monodeploy from '@monodeploy/node'

try {
    const config: MonodeployConfiguration = {
        noRegistry: true
    }
    const changeset = await monodeploy(config)
} catch (err) {
    console.error(err)
}
```

run `yarn monodeploy --config-file monodeploy.config.js `

and get 

```
Error: Unable to parse monodeploy config from: monodeploy.config.js.

Your application tried to access monodeploy.config.js, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: monodeploy.config.js (via "monodeploy.config.js")
Required by: /Users/matthaber/repos/matt-test-terraform/

Require stack:
- /Users/matthaber/repos/matt-test-terraform/.yarn/cache/monodeploy-npm-2.3.0-73b88a750a-b0994a0d18.zip/node_modules/monodeploy/lib/readConfigFile.js
- /Users/matthaber/repos/matt-test-terraform/.yarn/cache/monodeploy-npm-2.3.0-73b88a750a-b0994a0d18.zip/node_modules/monodeploy/lib/cli.js
    at readConfigFile (/Users/matthaber/repos/matt-test-terraform/.yarn/cache/monodeploy-npm-2.3.0-73b88a750a-b0994a0d18.zip/node_modules/monodeploy/lib/readConfigFile.js:23:13)
    at /Users/matthaber/repos/matt-test-terraform/.yarn/cache/monodeploy-npm-2.3.0-73b88a750a-b0994a0d18.zip/node_modules/monodeploy/lib/cli.js:92:79
    at Object.<anonymous> (/Users/matthaber/repos/matt-test-terraform/.yarn/cache/monodeploy-npm-2.3.0-73b88a750a-b0994a0d18.zip/node_modules/monodeploy/lib/cli.js:121:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.external_module_.Module._load (/Users/matthaber/repos/matt-test-terraform/.pnp.js:13144:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
Command failed: /Users/matthaber/.nvm/nvm-exec /Users/matthaber/.yvm/versions/v1.22.5/bin/yarn.js monodeploy --config-file monodeploy.config.js
```

i tried passing it as a relative pass and then get...

`yarn monodeploy --config-file ./monodeploy.config.js `
```
Error: Unable to parse monodeploy config from: ./monodeploy.config.js.

Cannot use import statement outside a module
    at readConfigFile (/Users/matthaber/repos/matt-test-terraform/.yarn/cache/monodeploy-npm-2.3.0-73b88a750a-b0994a0d18.zip/node_modules/monodeploy/lib/readConfigFile.js:23:13)
    at /Users/matthaber/repos/matt-test-terraform/.yarn/cache/monodeploy-npm-2.3.0-73b88a750a-b0994a0d18.zip/node_modules/monodeploy/lib/cli.js:92:79
    at Object.<anonymous> (/Users/matthaber/repos/matt-test-terraform/.yarn/cache/monodeploy-npm-2.3.0-73b88a750a-b0994a0d18.zip/node_modules/monodeploy/lib/cli.js:121:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.external_module_.Module._load (/Users/matthaber/repos/matt-test-terraform/.pnp.js:13144:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
Command failed: /Users/matthaber/.nvm/nvm-exec /Users/matthaber/.yvm/versions/v1.22.5/bin/yarn.js monodeploy --config-file ./monodeploy.config.js
```

to my knowledge, the config i used is a copy of the one in the docs, so /should/ work?

**Comment by noahnu** [comment]
Likely an issue with the way we create the full path: `path.resolve(cwd, filename)` needs to be  joined to a join.

**Comment by noahnu** [comment]
The relative path will work, your config format is incorrect. You should do:

```
module.exports = { config goes here }
```

for example:

```
module.exports = {
    noRegistry: true
}
```
