### ISSUE TITLE
Monodeploy does not work on Windows: "Error: Workspace not found"

### ISSUE THREAD

**Issue by rxliuli** [tophat/monodeploy#420]
**Describe the bug**

```sh
$ yarn monodeploy --dry-run
[Exec] Fetching most recent tag failed, falling back to HEAD
➤ YN0001: Error: Workspace not found (C:\Users\rxliuli\Code\Web\liuli-util\monodeploy.config.js)
    at Project.getWorkspaceByFilePath (C:\Users\rxliuli\Code\Web\liuli-util\node_modules\@yarnpkg\core\lib\Project.js:289:19)
    at C:\Users\rxliuli\Code\Web\liuli-util\node_modules\@monodeploy\versions\lib\getExplicitVersionStrategies.js:35:51
    at Array.reduce (<anonymous>)
    at getModifiedPackages (C:\Users\rxliuli\Code\Web\liuli-util\node_modules\@monodeploy\versions\lib\getExplicitVersionStrategies.js:32:47)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.getExplicitVersionStrategies (C:\Users\rxliuli\Code\Web\liuli-util\node_modules\@monodeploy\versions\lib\getExplicitVersionStrategies.js:67:30)
    at async pipeline (C:\Users\rxliuli\Code\Web\liuli-util\node_modules\@monodeploy\node\lib\index.js:76:39)
    at async Function.start (C:\Users\rxliuli\Code\Web\liuli-util\node_modules\@yarnpkg\core\lib\StreamReport.js:132:13)
    at async Object.monodeploy [as default] (C:\Users\rxliuli\Code\Web\liuli-util\node_modules\@monodeploy\node\lib\index.js:179:20)
    at async C:\Users\rxliuli\Code\Web\liuli-util\node_modules\monodeploy\lib\cli.js:210:9
➤ YN0001: Error: Workspace not found (C:\Users\rxliuli\Code\Web\liuli-util\package.json)
    at Project.getWorkspaceByFilePath (C:\Users\rxliuli\Code\Web\liuli-util\node_modules\@yarnpkg\core\lib\Project.js:289:19)
    at C:\Users\rxliuli\Code\Web\liuli-util\node_modules\@monodeploy\versions\lib\getExplicitVersionStrategies.js:35:51
    at Array.reduce (<anonymous>)
    at getModifiedPackages (C:\Users\rxliuli\Code\Web\liuli-util\node_modules\@monodeploy\versions\lib\getExplicitVersionStrategies.js:32:47)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.getExplicitVersionStrategies (C:\Users\rxliuli\Code\Web\liuli-util\node_modules\@monodeploy\versions\lib\getExplicitVersionStrategies.js:67:30)
    at async pipeline (C:\Users\rxliuli\Code\Web\liuli-util\node_modules\@monodeploy\node\lib\index.js:76:39)
    at async Function.start (C:\Users\rxliuli\Code\Web\liuli-util\node_modules\@yarnpkg\core\lib\StreamReport.js:132:13)
    at async Object.monodeploy [as default] (C:\Users\rxliuli\Code\Web\liuli-util\node_modules\@monodeploy\node\lib\index.js:179:20)
    at async C:\Users\rxliuli\Code\Web\liuli-util\node_modules\monodeploy\lib\cli.js:210:9
➤ YN0001: Error: Workspace not found (C:\Users\rxliuli\Code\Web\liuli-util\yarn.lock)
    at Project.getWorkspaceByFilePath (C:\Users\rxliuli\Code\Web\liuli-util\node_modules\@yarnpkg\core\lib\Project.js:289:19)
    at C:\Users\rxliuli\Code\Web\liuli-util\node_modules\@monodeploy\versions\lib\getExplicitVersionStrategies.js:35:51
    at Array.reduce (<anonymous>)
    at getModifiedPackages (C:\Users\rxliuli\Code\Web\liuli-util\node_modules\@monodeploy\versions\lib\getExplicitVersionStrategies.js:32:47)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.getExplicitVersionStrategies (C:\Users\rxliuli\Code\Web\liuli-util\node_modules\@monodeploy\versions\lib\getExplicitVersionStrategies.js:67:30)
    at async pipeline (C:\Users\rxliuli\Code\Web\liuli-util\node_modules\@monodeploy\node\lib\index.js:76:39)
    at async Function.start (C:\Users\rxliuli\Code\Web\liuli-util\node_modules\@yarnpkg\core\lib\StreamReport.js:132:13)
    at async Object.monodeploy [as default] (C:\Users\rxliuli\Code\Web\liuli-util\node_modules\@monodeploy\node\lib\index.js:179:20)
    at async C:\Users\rxliuli\Code\Web\liuli-util\node_modules\monodeploy\lib\cli.js:210:9
➤ YN0000: No packages need to be updated.
➤ YN0000: ┌ Fetching Workspace Information
➤ YN0000: └ Completed
➤ YN0000: ┌ Patching Package Manifests
➤ YN0000: └ Completed
➤ YN0000: ┌ Publishing Packages
➤ YN0000: └ Completed
➤ YN0000: ┌ Updating Change Files
➤ YN0000: └ Completed
➤ YN0000: [Dry Run] Monodeploy completed successfully
➤ YN0000: ┌ Cleaning Up
➤ YN0000: └ Completed
➤ YN0000: Failed with errors in 1s 142ms
Error: Monodeploy failed
    at Object.monodeploy [as default] (C:\Users\rxliuli\Code\Web\liuli-util\node_modules\@monodeploy\node\lib\index.js:188:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async C:\Users\rxliuli\Code\Web\liuli-util\node_modules\monodeploy\lib\cli.js:210:9
```

**To reproduce**

1. clone <https://github.com/rxliuli/liuli-utils/tree/bug_monodeploy_demo>
2. run `yarn && yarn monodeploy --dry-run`

**Expected behavior**

Publish all packages to npm in a manner similar to lerna publish

**Screenshots**

**Environment (please complete the following information):**

- OS: Windows 10
- Monodeploy Version: ^2.8.3
- Node Version: v14.17.0

**Additional context**

**Comment by rxliuli** [comment]
> Can't reproduce on Mac. Likely a Windows compatibility issue. There may be some uses of path that can be changed to PortablePath.

Yes it looks so

https://yarnpkg.com/api/classes/yarnpkg_core.project.html#getworkspacebyfilepath
C:\Users\rxliuli\Code\Web\liuli-util\node_modules\@monodeploy\versions\lib\getExplicitVersionStrategies.js#34:18

**Comment by noahnu** [comment]
We have a couple e2e tests. I can have them run on windows to ensure full compatibility

**Comment by noahnu** [comment]
@rxliuli Sorry about the long turnaround. We don't use windows internally and my personal computer is a ubuntu, so it's a been a bit difficult to test this out.

CI now runs the unit/integration tests against windows. Some more work is required to run the e2es against windows (need to provide an alternative for the mock npm registry). The non-e2e coverage is pretty extensive though. You can try this out on the pre-release:

```
yarn add -D monodeploy@^2.8.12-rc.0
```

Out of curiosity, was this just discovered during local use, or were you trying to run monodeploy in a windows CI environment as well?

**Comment by noahnu** [comment]
Since we now have an e2e run against windows, I'll close this issue.

**Comment by rxliuli** [comment]
> Since we now have an e2e run against windows, I'll close this issue.

Sorry, I no longer use yarn2 and its surrounding plugins as monorepo management tools
