### ISSUE TITLE
No longer able to release non-PnP project

### ISSUE THREAD

**Issue by markandrus** [tophat/monodeploy#444]
**Describe the bug**

I am using `nodeLinker: node-modules`, although I do check in the `.yarn/cache` (so not-quite-zero-installs). The change in https://github.com/tophat/monodeploy/pull/438 seems to break my build, because I do not have a .pnp.cjs file:

```
➤ YN0001: │ Error: Executing 'git add yarn.lock package.json "**/package.json" .pnp.cjs' failed with code: 128

fatal: pathspec '.pnp.cjs' did not match any files

    at exec (/home/circleci/project/node_modules/@monodeploy/io/lib/exec.js:35:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async git (/home/circleci/project/node_modules/@monodeploy/git/lib/gitCommands.js:28:12)
    at async gitAdd (/home/circleci/project/node_modules/@monodeploy/git/lib/gitCommands.js:126:5)
    at async commitPublishChanges (/home/circleci/project/node_modules/@monodeploy/publish/lib/commitPublishChanges.js:32:9)
    at async /home/circleci/project/node_modules/@monodeploy/node/lib/index.js:169:21
    at async StreamReport.startTimerPromise (/home/circleci/project/node_modules/@yarnpkg/core/lib/StreamReport.js:220:20)
    at async pipeline (/home/circleci/project/node_modules/@monodeploy/node/lib/index.js:167:13)
    at async Function.start (/home/circleci/project/node_modules/@yarnpkg/core/lib/StreamReport.js:133:13)
    at async monodeploy (/home/circleci/project/node_modules/@monodeploy/node/lib/index.js:193:20)
```

**To reproduce**

See above.

**Expected behavior**

The file .pnp.cjs is only `git add`-ed if it exists.

**Screenshots**

N/A

**Environment (please complete the following information):**

- OS: macOS
- Monodeploy Version: @monodeploy/publish@0.6.0 
- Node Version: 16

**Additional context**

If I force the use of @monodeploy/publish@0.5.15, then it still works.

**Comment by noahnu** [comment]
We should add an end to end test for the node modules linker

**Comment by noahnu** [comment]
Fixed in https://github.com/tophat/monodeploy/pull/445
