### ISSUE TITLE
Verify whether git credentials are working before deploying

### ISSUE THREAD

**Issue by EdieLemoine** [tophat/monodeploy#523]
**Is your feature request related to a problem? Please describe.**

Monodeploy does not check if the git credentials are working before proceeding with steps like npm publish. This causes a release run to push new version(s) to npm, without being able to create a release commit, a tag and a GitHub release (if using the GitHub plugin).

**Describe the solution you'd like**

Monodeploy should verify whether pushing is possible and throw an error if not before deploy steps are executed.

**Additional context**

This caused me to accidentally ruin the [1.0.0 release of one of my monorepos](https://www.npmjs.com/package/@myparcel-eslint/eslint-config) because I didn't notice this until I had published 1.1.0 and 1.2.0 by rerunning monodeploy trying to fix the git auth :(

https://github.com/myparcelnl/eslint/actions/runs/3470822640/jobs/5799508333

Pasting the logs here too in case they expire:
```
Run yarn monodeploy --log-level 0
[Exec] git log --format=%H -n 1 HEAD
➤ YN0000: [Config] Using:
➤ YN0000: {
  "registryUrl": "https://registry.npmjs.org",
  "noRegistry": false,
  "registryMode": "npm",
  "cwd": "/home/runner/work/eslint/eslint",
  "dryRun": false,
  "git": {
    "baseBranch": "3580814308a03b2efb7b94f9fdd628109e4a1a24",
    "commitSha": "7a2f431cc00259e46f55df2529f30829ec29f53e",
    "remote": "origin",
    "push": true,
    "tag": true
  },
  "conventionalChangelogConfig": "conventional-changelog-conventionalcommits",
  "applyChangeset": false,
  "changelogFilename": "<packageDir>/CHANGELOG.md",
  "changesetIgnorePatterns": [
    "**/*.test.ts",
    "**/*.test.js"
  ],
  "forceWriteChangeFiles": false,
  "access": "infer",
  "persistVersions": true,
  "autoCommit": true,
  "autoCommitMessage": "chore: release [skip ci]",
  "topological": false,
  "topologicalDev": false,
  "jobs": 0,
  "maxConcurrentReads": 0,
  "maxConcurrentWrites": 0,
  "plugins": [
    "@monodeploy/plugin-github"
  ],
  "prerelease": false,
  "prereleaseId": "main",
  "prereleaseNPMTag": "main"
}
➤ YN0000: [Exec] git log 3580814308a03b2efb7b94f9fdd628109e4a1a24..7a2f431cc00259e46f55df2529f30829ec29f53e --format=%H%n%B%n-----------------monodeploy-----------------
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root 7a2f431cc00259e46f55df2529f30829ec29f53e
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root e85cdd36d1beb67d17deee7f1ba763f81b1b7643
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root 5d18a8b89d1fdb86bd66d769b4ba2fd48fe17381
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root 38f340d3b34d37ae0a3487b3f7b58cecb5a1e2cb
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root 3d71fdd60ac38656fc9c8c2dd835bac1e620dac9
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root 1a9efd3c5b552da01aed7876f44758f9b4a0db01
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root 6c4a23[11](https://github.com/myparcelnl/eslint/actions/runs/3470822640/jobs/5799508333#step:7:12)cae36b9313a5181993b289e882e228d5
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root 62660ac31435c5506f52b0675941183924553e19
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root 95fdbb3a6a04429eb338795b100244b033a68fc6
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root 949b635dcb86d22f0b8cbea68a739287ee163b46
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root 45689240b8143816a6e7cca25b8ef75dcb24c624
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root 2d45c2d3a06cf0a3ed17a6113642246ea7f0171e
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root d7813e2a717b08703535781d6473f7097d9e7c05
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root c35073842deb9cbaedb0bc3a9c87c1ddbd9abc15
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root 394f4c99897e5afc449b19684eb0488c79f2062e
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root f0fe77bd13668afdc7472d474aa967771945ae99
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root 596d88fafc97cb9a747f43836322fbfce4c0a276
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root cfc6dfbae71f5c5d80d6db16b2cdca3ddbf56fd2
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root 50a7823fd22c365db635a24c5a86a3fff5dcba4a
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root e51472a1f3521d0efc778824f0efd31d4f4c2540
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root ce423c94dd52891431fcb0a6374c5a[12](https://github.com/myparcelnl/eslint/actions/runs/3470822640/jobs/5799508333#step:7:13)2ad8d9f2
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root f1a45bd1aa7aaef08e944c7f9061e3514906768e
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root 3aeb69bb62289db77570def64e8bf8f2b1f1b7a5
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root b415bdb8f86b497feccdeae52123058335889063
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root 99ae5a866389101f92e0b7ea077306d9dabb44e4
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root a187129bbf396703ab72ea3872ce71a9f199e743
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root 691e1dac244c5a8de9755e911b2d5c92bb84dde6
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root 667fec0b715402a3e6237acbe4cc3d8e23a41244
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root 74610129ebbb361aad91c3df0525d78b9dc1212e
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root 506a2329ecdfa66ff884c72ee945cbb6ba22386f
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root b49239c07bf7cc282838ffb064979acfd504f382
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root dca84bf7e4a15a82d987c7abe502f051ad0eda25
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root 8521814e89e4245ef8044f72b431240494766ae6
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root 6d068e1f0997c95c10e924f8867603b8b8c81a41
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root f256d8a05c10a716eb73447f9c9f7a21d31a1b16
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root 7b209b1bd554f762c98a45345d2e700cfa31f690
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root 44bdfd031f24ced23d24905921651f34490693ce
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root 03027cb2210237423e0fa6ef57f5294d08148ba5
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root fb3568dde6af39ffe40783dc0b964a8cbf683291
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root 3e1cd720755749f72c9fc648b2a0a81c8b23c414
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root 9a6b5200589496895c0[13](https://github.com/myparcelnl/eslint/actions/runs/3470822640/jobs/5799508333#step:7:14)65c2dcaced6f152c92b
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root dea8e3d3f3fc0af36916e10fda282f[14](https://github.com/myparcelnl/eslint/actions/runs/3470822640/jobs/5799508333#step:7:15)c6e3f9f8
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root d8f40b4ba32dc8af0ea204e058d3441b8f6b658a
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root 21123ef549cb5743546afb06da1105d94ee889e8
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root 46d8819436e557c867a3f5b11a2aea8c8cde5d51
➤ YN0000: [Exec] git diff-tree --no-commit-id --name-only -r --root b377429190b21c05f302ebc6ba13f0e4653a0e50
➤ YN0000: [Savepoint] Saving working tree (key: /tmp/package-jsons-xFmnhF)
➤ YN0000: ┌ Determine New Versions
Determine New Versions
➤ YN0000: └ Completed
➤ YN0000: ┌ Determine Git Tags
Determine Git Tags
➤ YN0000: └ Completed
➤ YN0000: ┌ Generating Changeset
Generating Changeset
➤ YN0000: └ Completed in 0s 285ms
➤ YN0000: ┌ Fetching Workspace Information
Fetching Workspace Information
➤ YN0000: └ Completed
➤ YN0000: ┌ Updating Changelog
Updating Changelog
➤ YN0000: └ Completed
➤ YN0000: ┌ Patching Package Manifests
Patching Package Manifests
➤ YN0000: └ Completed
➤ YN0000: ┌ Updating Project State
Updating Project State
Resolution step
➤ YN0000: │ └ Completed in 0s 689ms
➤ YN0000: │ ┌ Fetch step
Fetch step
➤ YN0000: │ └ Completed in 0s 341ms
➤ YN0000: │ ┌ Link step
Link step
➤ YN0000: │ └ Completed in 0s 396ms

➤ YN0000: └ Completed in 1s 561ms
➤ YN0000: ┌ Committing Changes
Committing Changes
  ➤ YN0000: │ [Exec] git ls-files --modified
  ➤ YN0000: │ [Exec] git ls-files -o --exclude-standard
  ➤ YN0000: │ [Exec] git add yarn.lock packages/eslint-config-cypress/package.json packages/eslint-config-es5/package.json packages/eslint-config-es6/package.json packages/eslint-config-esnext/package.json packages/eslint-config-node/package.json packages/eslint-config-prettier-typescript-vue/package.json packages/eslint-config-prettier-typescript/package.json packages/eslint-config-prettier-vue/package.json packages/eslint-config-prettier/package.json packages/eslint-config-tailwindcss/package.json packages/eslint-config-typescript-vue/package.json packages/eslint-config-typescript/package.json packages/eslint-config-vue/package.json packages/eslint-config-vue2/package.json packages/eslint-config-vue3/package.json packages/eslint-config/package.json packages/utils/package.json packages/eslint-config-cypress/CHANGELOG.md packages/eslint-config-es5/CHANGELOG.md packages/eslint-config-es6/CHANGELOG.md packages/eslint-config-esnext/CHANGELOG.md packages/eslint-config-node/CHANGELOG.md packages/eslint-config-prettier-typescript-vue/CHANGELOG.md packages/eslint-config-prettier-typescript/CHANGELOG.md packages/eslint-config-prettier-vue/CHANGELOG.md packages/eslint-config-prettier/CHANGELOG.md packages/eslint-config-tailwindcss/CHANGELOG.md packages/eslint-config-typescript-vue/CHANGELOG.md packages/eslint-config-typescript/CHANGELOG.md packages/eslint-config-vue/CHANGELOG.md packages/eslint-config-vue2/CHANGELOG.md packages/eslint-config-vue3/CHANGELOG.md packages/eslint-config/CHANGELOG.md packages/utils/CHANGELOG.md
  ➤ YN0000: │ [Exec] git commit -m "chore: release [skip ci]" -n
  ➤ YN0000: │ [Exec] git tag @myparcel-eslint/eslint-config@1.2.0 -m @myparcel-eslint/eslint-config@1.2.0
  ➤ YN0000: │ [Tag] @myparcel-eslint/eslint-config@1.2.0
  ➤ YN0000: │ [Exec] git tag @myparcel-eslint/eslint-config-cypress@1.2.0 -m @myparcel-eslint/eslint-config-cypress@1.2.0
  ➤ YN0000: │ [Tag] @myparcel-eslint/eslint-config-cypress@1.2.0
  ➤ YN0000: │ [Exec] git tag @myparcel-eslint/eslint-config-es5@1.2.0 -m @myparcel-eslint/eslint-config-es5@1.2.0
  ➤ YN0000: │ [Tag] @myparcel-eslint/eslint-config-es5@1.2.0
  ➤ YN0000: │ [Exec] git tag @myparcel-eslint/eslint-config-es6@1.2.0 -m @myparcel-eslint/eslint-config-es6@1.2.0
  ➤ YN0000: │ [Tag] @myparcel-eslint/eslint-config-es6@1.2.0
  ➤ YN0000: │ [Exec] git tag @myparcel-eslint/eslint-config-esnext@1.2.0 -m @myparcel-eslint/eslint-config-esnext@1.2.0
  ➤ YN0000: │ [Tag] @myparcel-eslint/eslint-config-esnext@1.2.0
  ➤ YN0000: │ [Exec] git tag @myparcel-eslint/eslint-config-node@1.2.0 -m @myparcel-eslint/eslint-config-node@1.2.0
  ➤ YN0000: │ [Tag] @myparcel-eslint/eslint-config-node@1.2.0
  ➤ YN0000: │ [Exec] git tag @myparcel-eslint/eslint-config-prettier@1.2.0 -m @myparcel-eslint/eslint-config-prettier@1.2.0
  ➤ YN0000: │ [Tag] @myparcel-eslint/eslint-config-prettier@1.2.0
  ➤ YN0000: │ [Exec] git tag @myparcel-eslint/eslint-config-prettier-typescript@1.2.0 -m @myparcel-eslint/eslint-config-prettier-typescript@1.2.0
  ➤ YN0000: │ [Tag] @myparcel-eslint/eslint-config-prettier-typescript@1.2.0
  ➤ YN0000: │ [Exec] git tag @myparcel-eslint/eslint-config-prettier-typescript-vue@1.2.0 -m @myparcel-eslint/eslint-config-prettier-typescript-vue@1.2.0
  ➤ YN0000: │ [Tag] @myparcel-eslint/eslint-config-prettier-typescript-vue@1.2.0
  ➤ YN0000: │ [Exec] git tag @myparcel-eslint/eslint-config-prettier-vue@1.2.0 -m @myparcel-eslint/eslint-config-prettier-vue@1.2.0
  ➤ YN0000: │ [Tag] @myparcel-eslint/eslint-config-prettier-vue@1.2.0
  ➤ YN0000: │ [Exec] git tag @myparcel-eslint/eslint-config-tailwindcss@1.2.0 -m @myparcel-eslint/eslint-config-tailwindcss@1.2.0
  ➤ YN0000: │ [Tag] @myparcel-eslint/eslint-config-tailwindcss@1.2.0
  ➤ YN0000: │ [Exec] git tag @myparcel-eslint/eslint-config-typescript@1.2.0 -m @myparcel-eslint/eslint-config-typescript@1.2.0
  ➤ YN0000: │ [Tag] @myparcel-eslint/eslint-config-typescript@1.2.0
  ➤ YN0000: │ [Exec] git tag @myparcel-eslint/eslint-config-typescript-vue@1.2.0 -m @myparcel-eslint/eslint-config-typescript-vue@1.2.0
  ➤ YN0000: │ [Tag] @myparcel-eslint/eslint-config-typescript-vue@1.2.0
  ➤ YN0000: │ [Exec] git tag @myparcel-eslint/eslint-config-vue@1.2.0 -m @myparcel-eslint/eslint-config-vue@1.2.0
  ➤ YN0000: │ [Tag] @myparcel-eslint/eslint-config-vue@1.2.0
  ➤ YN0000: │ [Exec] git tag @myparcel-eslint/eslint-config-vue2@1.2.0 -m @myparcel-eslint/eslint-config-vue2@1.2.0
  ➤ YN0000: │ [Tag] @myparcel-eslint/eslint-config-vue2@1.2.0
  ➤ YN0000: │ [Exec] git tag @myparcel-eslint/eslint-config-vue3@1.2.0 -m @myparcel-eslint/eslint-config-vue3@1.2.0
  ➤ YN0000: │ [Tag] @myparcel-eslint/eslint-config-vue3@1.2.0
  ➤ YN0000: │ [Exec] git tag @myparcel-eslint/utils@1.2.0 -m @myparcel-eslint/utils@1.2.0
  ➤ YN0000: │ [Tag] @myparcel-eslint/utils@1.2.0
  ➤ YN0000: │ [Exec] git pull --rebase --no-verify origin
  ➤ YN0000: │ [Exec] git log --format=%H -n 1 HEAD
➤ YN0000: └ Completed in 0s 6[15](https://github.com/myparcelnl/eslint/actions/runs/3470822640/jobs/5799508333#step:7:16)ms
➤ YN0000: ┌ Publishing Packages
Publishing Packages
  ➤ YN0000: │ [Publish] @myparcel-eslint/eslint-config (latest: 1.2.0, https://registry.npmjs.org; undefined)
  ➤ YN0000: │ [Publish] @myparcel-eslint/eslint-config-cypress (latest: 1.2.0, https://registry.npmjs.org; undefined)
  ➤ YN0000: │ [Publish] @myparcel-eslint/eslint-config-es5 (latest: 1.2.0, https://registry.npmjs.org; undefined)
  ➤ YN0000: │ [Publish] @myparcel-eslint/eslint-config-es6 (latest: 1.2.0, https://registry.npmjs.org; undefined)
  ➤ YN0000: │ [Publish] @myparcel-eslint/eslint-config-esnext (latest: 1.2.0, https://registry.npmjs.org; undefined)
  ➤ YN0000: │ [Publish] @myparcel-eslint/eslint-config-node (latest: 1.2.0, https://registry.npmjs.org; undefined)
  ➤ YN0000: │ [Publish] @myparcel-eslint/eslint-config-prettier (latest: 1.2.0, https://registry.npmjs.org; undefined)
  ➤ YN0000: │ [Publish] @myparcel-eslint/eslint-config-prettier-typescript (latest: 1.2.0, https://registry.npmjs.org; undefined)
  ➤ YN0000: │ [Publish] @myparcel-eslint/eslint-config-prettier-typescript-vue (latest: 1.2.0, https://registry.npmjs.org; undefined)
  ➤ YN0000: │ [Publish] @myparcel-eslint/eslint-config-prettier-vue (latest: 1.2.0, https://registry.npmjs.org; undefined)
  ➤ YN0000: │ [Publish] @myparcel-eslint/eslint-config-tailwindcss (latest: 1.2.0, https://registry.npmjs.org; undefined)
  ➤ YN0000: │ [Publish] @myparcel-eslint/eslint-config-typescript (latest: 1.2.0, https://registry.npmjs.org; undefined)
  ➤ YN0000: │ [Publish] @myparcel-eslint/eslint-config-typescript-vue (latest: 1.2.0, https://registry.npmjs.org; undefined)
  ➤ YN0000: │ [Publish] @myparcel-eslint/eslint-config-vue (latest: 1.2.0, https://registry.npmjs.org; undefined)
  ➤ YN0000: │ [Publish] @myparcel-eslint/eslint-config-vue2 (latest: 1.2.0, https://registry.npmjs.org; undefined)
  ➤ YN0000: │ [Publish] @myparcel-eslint/eslint-config-vue3 (latest: 1.2.0, https://registry.npmjs.org; undefined)
  ➤ YN0000: │ [Publish] @myparcel-eslint/utils (latest: 1.2.0, https://registry.npmjs.org; undefined)
  ➤ YN0000: │ [Publish] '@myparcel-eslint/eslint-config' published.
  ➤ YN0000: │ [Publish] '@myparcel-eslint/eslint-config-cypress' published.
  ➤ YN0000: │ [Publish] '@myparcel-eslint/eslint-config-es5' published.
  ➤ YN0000: │ [Publish] '@myparcel-eslint/eslint-config-es6' published.
  ➤ YN0000: │ [Publish] '@myparcel-eslint/eslint-config-esnext' published.
  ➤ YN0000: │ [Publish] '@myparcel-eslint/eslint-config-node' published.
  ➤ YN0000: │ [Publish] '@myparcel-eslint/eslint-config-prettier' published.
  ➤ YN0000: │ [Publish] '@myparcel-eslint/eslint-config-prettier-typescript' published.
  ➤ YN0000: │ [Publish] '@myparcel-eslint/eslint-config-prettier-typescript-vue' published.
  ➤ YN0000: │ [Publish] '@myparcel-eslint/eslint-config-prettier-vue' published.
  ➤ YN0000: │ [Publish] '@myparcel-eslint/eslint-config-tailwindcss' published.
  ➤ YN0000: │ [Publish] '@myparcel-eslint/eslint-config-typescript' published.
  ➤ YN0000: │ [Publish] '@myparcel-eslint/eslint-config-typescript-vue' published.
  ➤ YN0000: │ [Publish] '@myparcel-eslint/eslint-config-vue' published.
  ➤ YN0000: │ [Publish] '@myparcel-eslint/eslint-config-vue2' published.
  ➤ YN0000: │ [Publish] '@myparcel-eslint/eslint-config-vue3' published.
  ➤ YN0000: │ [Publish] '@myparcel-eslint/utils' published.
➤ YN0000: └ Completed in 22s 572ms
➤ YN0000: ┌ Pushing Commit
Pushing Commit
  ➤ YN0000: │ [Exec] git push --no-verify origin
  ➤ YN0001: │ Error: Executing 'git push --no-verify origin' failed with code: 128
  
  fatal: could not read Username for 'https://github.com': No such device or address
  
      at exec (/home/runner/work/eslint/eslint/node_modules/@monodeploy/io/lib/exec.js:35:11)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async git (/home/runner/work/eslint/eslint/node_modules/@monodeploy/git/lib/gitCommands.js:36:12)
      at async gitPush (/home/runner/work/eslint/eslint/node_modules/@monodeploy/git/lib/gitCommands.js:87:5)
      at async pushPublishCommit (/home/runner/work/eslint/eslint/node_modules/@monodeploy/publish/lib/commitPublishChanges.js:58:9)
      at async /home/runner/work/eslint/eslint/node_modules/@monodeploy/node/lib/index.js:238:[17](https://github.com/myparcelnl/eslint/actions/runs/3470822640/jobs/5799508333#step:7:18)
      at async StreamReport.startSectionPromise (/home/runner/work/eslint/eslint/node_modules/@yarnpkg/core/lib/StreamReport.js:[20](https://github.com/myparcelnl/eslint/actions/runs/3470822640/jobs/5799508333#step:7:21)5:20)
      at async pipeline (/home/runner/work/eslint/eslint/node_modules/@monodeploy/node/lib/index.js:[23](https://github.com/myparcelnl/eslint/actions/runs/3470822640/jobs/5799508333#step:7:24)5:13)
      at async Function.start (/home/runner/work/eslint/eslint/node_modules/@yarnpkg/core/lib/StreamReport.js:101:13)
      at async monodeploy (/home/runner/work/eslint/eslint/node_modules/@monodeploy/node/lib/index.js:[26](https://github.com/myparcelnl/eslint/actions/runs/3470822640/jobs/5799508333#step:7:27)1:20)
➤ YN0000: └ Completed
➤ YN0000: ┌ Cleaning Up
Cleaning Up
  ➤ YN0000: │ [Savepoint] Deleting temporary savepoint files
➤ YN0000: └ Completed
➤ YN0000: Failed with errors in [29](https://github.com/myparcelnl/eslint/actions/runs/3470822640/jobs/5799508333#step:7:30)s 9[88](https://github.com/myparcelnl/eslint/actions/runs/3470822640/jobs/5799508333#step:7:89)ms
Error: Process completed with exit code 1.
```

**Comment by noahnu** [comment]
Makes sense to me. Any ideas how we can verify credentials? Should we do this in dry run as well?

And are you interested in contributing this feature? (If so, I can point you in the right direction)

**Comment by noahnu** [comment]
> ruin the 1.0.0 release of one of my monorepos

Going off memory, I think you have 24 hours to delete a release from npm.

**Comment by EdieLemoine** [comment]
@noahnu I know, but it doesn't allow you to republish the same `name@version` ever again :/

I'd like to contribute, I glanced at the repository but I didn't spot the right place to do it fast enough to warrant making a pr before an issue :) 

Semantic release does it by `git push --dry-run`, which some people on StackOverflow say does not work, but it does seem to work for me.

One of my repositories:

```bash
git push --dry-run --no-verify https://github.com/edielemoine/eslint.git HEAD:test
```

```
To https://github.com/edielemoine/eslint.git
 * [new branch]      HEAD -> test
```

A repository I can't push to:

```bash
git push --dry-run --no-verify https://github.com/eslint/eslint.git HEAD:test
```

```
remote: Permission to eslint/eslint.git denied to EdieLemoine.
fatal: unable to access 'https://github.com/eslint/eslint.git/': The requested URL returned error: 403
```

**Comment by noahnu** [comment]
> I glanced at the repository but I didn't spot the right place

All git commands live in this file https://github.com/tophat/monodeploy/blob/main/packages/git/src/gitCommands.ts which must also be duplicated in the [mocks](https://github.com/tophat/monodeploy/blob/main/__mocks__/%40monodeploy/git.ts). You'd add a new command to verify push permissions.

The monodeploy pipeline is defined in this file: https://github.com/tophat/monodeploy/blob/main/packages/node/src/index.ts.

You could do the check in a stage before the publish to npm here: https://github.com/tophat/monodeploy/blob/03c45dd411127d56afcfa2933d663b2991425af3/packages/node/src/index.ts#L288 or possibly at the start of the pipeline somewhere around https://github.com/tophat/monodeploy/blob/03c45dd411127d56afcfa2933d663b2991425af3/packages/node/src/index.ts#L117.

The check should only run if `config.git.push` is true.

An alternative approach would be to run the "verify git permissions" check in place of the real `git push` when in dry run: https://github.com/tophat/monodeploy/blob/03c45dd411127d56afcfa2933d663b2991425af3/packages/node/src/index.ts#L308 and https://github.com/tophat/monodeploy/blob/03c45dd411127d56afcfa2933d663b2991425af3/packages/publish/src/commitPublishChanges.ts#L73

**Comment by EdieLemoine** [comment]
Thanks, just opened a pr! :)

**Comment by noahnu** [comment]
Some enhancements in https://github.com/tophat/monodeploy/releases/tag/monodeploy%403.4.0
